"use client";

import React, { useState } from "react";
import { FileText, Sparkles, Download, Copy, Check, BookOpen, Layers, ArrowRight } from "lucide-react";
import { useLibrary } from "@/context/LibraryContext";
import { useToast } from "@/context/ToastContext";
import { LiteratureReview } from "@/lib/types";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { api } from "@/lib/api";

export default function LiteratureReviewPage() {
  const { papers, selectedPaperIds, getSelectedPapers } = useLibrary();
  const { showToast } = useToast();

  const [topic, setTopic] = useState("Efficient Parameter Adaptation and Grounded Knowledge Retrieval in Foundation Models");
  const [review, setReview] = useState<LiteratureReview | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  const selectedPapers = getSelectedPapers();

  const handleGenerate = async () => {
    if (!topic.trim() || isGenerating) return;

    setIsGenerating(true);
    try {
      const data = await api.generateLiteratureReview(topic.trim(), selectedPapers.length > 0 ? selectedPapers : papers);
      setReview(data);
      showToast({
        type: "success",
        title: "Literature Review Generated",
        message: "Structured thematic review ready for export."
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportMarkdown = () => {
    if (!review) return;

    let md = `# Literature Review: ${review.topic}\n\n`;
    md += `*Generated by ResearchGPT on ${new Date(review.createdAt).toLocaleDateString()}*\n\n`;
    md += `## 1. Executive Summary\n${review.executiveSummary}\n\n`;

    md += `## 2. Thematic Categorization & Taxonomy\n`;
    review.themes.forEach(theme => {
      md += `### ${theme.name}\n${theme.description}\n\n`;
      theme.papers.forEach(p => {
        md += `- **${p.title}**: ${p.contribution}\n`;
      });
      md += `\n`;
    });

    md += `## 3. Methodological Landscape\n${review.methodologicalLandscape}\n\n`;

    md += `## 4. Critical Research Gaps\n`;
    review.criticalGaps.forEach(gap => {
      md += `- ${gap}\n`;
    });
    md += `\n`;

    md += `## 5. Future Directions\n`;
    review.futureDirections.forEach(dir => {
      md += `- ${dir}\n`;
    });
    md += `\n`;

    md += `## 6. References\n`;
    review.bibliography.forEach(b => {
      md += `- ${b.formattedCitation}\n`;
    });

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `literature-review-${topic.slice(0, 25).replace(/\s+/g, "-")}.md`;
    a.click();
    URL.revokeObjectURL(url);

    showToast({
      type: "success",
      title: "Exported",
      message: "Literature review downloaded as Markdown."
    });
  };

  const handleCopyReview = () => {
    if (!review) return;
    let fullText = `${review.topic}\n\nExecutive Summary:\n${review.executiveSummary}\n\nMethodology:\n${review.methodologicalLandscape}\n\nCritical Gaps:\n${review.criticalGaps.join("\n")}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    showToast({
      type: "success",
      title: "Copied to Clipboard",
      message: "Full literature review copied."
    });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-fade-in">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
              Structured Literature Review Generator
            </h1>
            <Badge variant="primary" size="sm">
              Publication Ready
            </Badge>
          </div>
          <p className="text-xs sm:text-sm text-zinc-500">
            Synthesize themes, methodological landscapes, critical research gaps, and formatted reference lists across your corpus.
          </p>
        </div>

        {review && (
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={handleCopyReview}
              leftIcon={copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            >
              {copied ? "Copied" : "Copy"}
            </Button>
            <Button
              size="sm"
              variant="primary"
              onClick={handleExportMarkdown}
              leftIcon={<Download className="w-3.5 h-3.5" />}
            >
              Export Review (.md)
            </Button>
          </div>
        )}
      </div>

      {/* Configuration Box */}
      <div className="p-5 sm:p-6 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-md space-y-4">
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-zinc-500 mb-2">
            Research Review Topic & Synthesis Scope
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              value={topic}
              onChange={e => setTopic(e.target.value)}
              placeholder="e.g., 'Attention mechanisms and parameter-efficient fine-tuning in neural language models'..."
              className="flex-1 px-4 py-2.5 rounded-xl border bg-zinc-50 dark:bg-zinc-800/60 border-zinc-200 dark:border-zinc-700/60 text-xs sm:text-sm text-zinc-900 dark:text-zinc-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
            <Button
              size="md"
              variant="primary"
              disabled={!topic.trim() || isGenerating}
              isLoading={isGenerating}
              onClick={handleGenerate}
              leftIcon={<Sparkles className="w-4 h-4" />}
            >
              Generate Review
            </Button>
          </div>
        </div>

        <div className="flex items-center gap-2 text-xs text-zinc-500">
          <BookOpen className="w-4 h-4 text-indigo-500" />
          <span>Synthesizing across <span className="font-semibold text-zinc-800 dark:text-zinc-200">{selectedPapers.length > 0 ? selectedPapers.length : papers.length} papers</span> currently in your active workspace.</span>
        </div>
      </div>

      {/* Generated Review Display */}
      {isGenerating ? (
        <div className="p-12 text-center rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 space-y-3 animate-pulse">
          <Sparkles className="w-10 h-10 text-indigo-500 animate-spin mx-auto" />
          <h3 className="text-base font-bold text-zinc-800 dark:text-zinc-200">
            Synthesizing Structured Literature Review...
          </h3>
          <p className="text-xs text-zinc-400 max-w-sm mx-auto">
            Categorizing thematic hierarchies, extracting empirical contributions, and compiling citation references.
          </p>
        </div>
      ) : review ? (
        <div className="p-8 sm:p-12 rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-2xl space-y-8 animate-slide-up font-serif">
          {/* Review Title */}
          <div className="border-b border-zinc-200 dark:border-zinc-800 pb-6 space-y-2 font-sans">
            <Badge variant="primary" size="sm">
              Synthesized Academic Review
            </Badge>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-zinc-900 dark:text-zinc-100 tracking-tight leading-tight">
              {review.topic}
            </h2>
            <p className="text-xs text-zinc-400">
              Compiled on {new Date(review.createdAt).toLocaleDateString()} • Grounded in {review.bibliography.length} peer-reviewed publications
            </p>
          </div>

          {/* Section 1: Executive Summary */}
          <section className="space-y-3">
            <h3 className="text-lg font-bold font-sans text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-xs font-mono">1</span>
              Executive Summary & Scope
            </h3>
            <p className="text-sm sm:text-base leading-relaxed text-zinc-700 dark:text-zinc-300">
              {review.executiveSummary}
            </p>
          </section>

          {/* Section 2: Thematic Taxonomy */}
          <section className="space-y-4">
            <h3 className="text-lg font-bold font-sans text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-xs font-mono">2</span>
              Thematic Taxonomy & Categorization
            </h3>
            <div className="space-y-4">
              {review.themes.map((theme, i) => (
                <div
                  key={i}
                  className="p-5 rounded-2xl bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200 dark:border-zinc-700/60 space-y-2 font-sans"
                >
                  <h4 className="font-bold text-sm text-zinc-900 dark:text-zinc-100">
                    {theme.name}
                  </h4>
                  <p className="text-xs text-zinc-600 dark:text-zinc-300 leading-relaxed font-serif">
                    {theme.description}
                  </p>
                  <div className="pt-2 space-y-1.5">
                    {theme.papers.map((p, idx) => (
                      <div key={idx} className="flex items-start gap-2 text-xs text-zinc-700 dark:text-zinc-300">
                        <span className="text-indigo-500 font-bold">•</span>
                        <span>
                          <strong className="text-zinc-900 dark:text-zinc-100">{p.title}</strong>: {p.contribution}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Section 3: Methodological Landscape */}
          <section className="space-y-3">
            <h3 className="text-lg font-bold font-sans text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-xs font-mono">3</span>
              Methodological Landscape
            </h3>
            <p className="text-sm sm:text-base leading-relaxed text-zinc-700 dark:text-zinc-300">
              {review.methodologicalLandscape}
            </p>
          </section>

          {/* Section 4: Critical Research Gaps */}
          <section className="space-y-3 font-sans">
            <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <span className="w-6 h-6 rounded-lg bg-amber-100 dark:bg-amber-950 text-amber-600 dark:text-amber-400 flex items-center justify-center text-xs font-mono">4</span>
              Critical Research Gaps in Literature
            </h3>
            <div className="p-5 rounded-2xl bg-amber-50/50 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-800/40 space-y-2">
              {review.criticalGaps.map((gap, i) => (
                <div key={i} className="flex items-start gap-2 text-xs text-amber-900 dark:text-amber-200 leading-relaxed">
                  <span className="text-amber-500 font-bold">⚠️</span>
                  <span>{gap}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Section 5: Future Directions */}
          <section className="space-y-3 font-sans">
            <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <span className="w-6 h-6 rounded-lg bg-emerald-100 dark:bg-emerald-950 text-emerald-600 dark:text-emerald-400 flex items-center justify-center text-xs font-mono">5</span>
              Future Research Directions
            </h3>
            <div className="p-5 rounded-2xl bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-200/60 dark:border-emerald-800/40 space-y-2">
              {review.futureDirections.map((dir, i) => (
                <div key={i} className="flex items-start gap-2 text-xs text-emerald-900 dark:text-emerald-200 leading-relaxed">
                  <span className="text-emerald-500 font-bold">🚀</span>
                  <span>{dir}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Section 6: References */}
          <section className="space-y-3 font-sans pt-4 border-t border-zinc-200 dark:border-zinc-800">
            <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <span className="w-6 h-6 rounded-lg bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-xs font-mono">6</span>
              Synthesized References & Bibliographies
            </h3>
            <div className="space-y-2">
              {review.bibliography.map((b, idx) => (
                <div
                  key={idx}
                  className="p-3 rounded-xl bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/60 dark:border-zinc-700/60 text-xs font-serif text-zinc-700 dark:text-zinc-300"
                >
                  {b.formattedCitation}
                </div>
              ))}
            </div>
          </section>
        </div>
      ) : null}
    </div>
  );
}
